bin: retire 'git pub' in favor of 'git lore'

diff --git a/bin/git-lore b/bin/git-lore
--- a/bin/git-lore
+++ b/bin/git-lore
@@ -3,7 +3,7 @@
 set -e
 
 if [ 1 -ne $# ]; then
-  echo >&2 "fatal: expected public-inbox URL, aborting ..."
+  echo >&2 "fatal: expected lore.kernel.org URL, aborting ..."
   exit 1
 fi
 
